class_name TrackData
extends RefCounted
## Track definition (control points) + generated geometry.
## The editable data is just `points` (closed centerline control points, meters), `width`, `sectors`.
## Everything else (samples, curvature, corners, overtaking zones, stats) is generated by build().

const FORMAT := 1
const SAMPLE_STEP := 4.0          # meters between generated centerline samples
const SPLINE_SUBDIV := 24
const CURVATURE_WINDOW := 4       # samples each side used to smooth curvature

var id: String = ""
var name: String = ""
var location: String = ""
var width: float = 13.0
var default_laps: int = 12
var sectors: Array = [0.333, 0.667]   # fractions of lap where sector 2 and 3 begin
var points: PackedVector2Array = PackedVector2Array()
var builtin: bool = false

# --- generated ---
var samples: PackedVector2Array = PackedVector2Array()
var tangents: PackedVector2Array = PackedVector2Array()
var normals: PackedVector2Array = PackedVector2Array()
var curvature: PackedFloat32Array = PackedFloat32Array()   # signed 1/m
var radius: PackedFloat32Array = PackedFloat32Array()      # m (smoothed, capped)
var length: float = 0.0
var step: float = SAMPLE_STEP
var corners: Array = []           # [{start, apex, end, min_radius, dir}]
var overtake_zones: Array = []    # [{index, strength}]  braking zones after straights
var ref_profile: PackedFloat32Array = PackedFloat32Array()  # reference car speed profile
var corner_start_at: PackedInt32Array = PackedInt32Array()  # per sample: corner index starting here, else -1
var zone_at: PackedInt32Array = PackedInt32Array()          # per sample: overtake zone index within 3 samples ahead, else -1
var stats: Dictionary = {}
var bounds: Rect2 = Rect2()


static func from_dict(d: Dictionary) -> TrackData:
	var t := TrackData.new()
	t.id = d.get("id", "")
	t.name = d.get("name", "Unnamed")
	t.location = d.get("location", "")
	t.width = float(d.get("width", 13))
	t.default_laps = int(d.get("default_laps", 12))
	t.sectors = d.get("sectors", [0.333, 0.667]).duplicate()
	t.builtin = bool(d.get("builtin", false))
	for p in d.get("points", []):
		t.points.append(Vector2(float(p[0]), float(p[1])))
	t.build()
	return t


static func load_id(track_id: String) -> TrackData:
	var d := DataDB.get_track(track_id)
	if d.is_empty():
		push_error("Track not found: " + track_id)
		return null
	return from_dict(d)


func to_dict() -> Dictionary:
	var pts := []
	for p in points:
		pts.append([snappedf(p.x, 0.1), snappedf(p.y, 0.1)])
	return {"format": FORMAT, "id": id, "name": name, "location": location, "width": width,
		"default_laps": default_laps, "sectors": sectors, "points": pts}


# ---------------------------------------------------------------- geometry

func build() -> void:
	samples.clear(); tangents.clear(); normals.clear(); curvature.clear(); radius.clear()
	corners.clear(); overtake_zones.clear()
	if points.size() < 3:
		length = 0.0
		return
	var dense := _spline_dense()
	_resample(dense)
	_compute_curvature()
	_detect_corners()
	ref_profile = PerformanceModel.speed_profile(self, PerformanceModel.reference_params())
	_detect_overtake_zones()
	_build_lookups()
	_compute_stats()


## Closed centripetal Catmull-Rom through all control points.
func _spline_dense() -> PackedVector2Array:
	var out := PackedVector2Array()
	var n := points.size()
	for i in n:
		var p0 := points[(i - 1 + n) % n]
		var p1 := points[i]
		var p2 := points[(i + 1) % n]
		var p3 := points[(i + 2) % n]
		for s in SPLINE_SUBDIV:
			out.append(_catmull(p0, p1, p2, p3, float(s) / SPLINE_SUBDIV))
	return out


static func _catmull(p0: Vector2, p1: Vector2, p2: Vector2, p3: Vector2, t: float) -> Vector2:
	# centripetal parameterisation (alpha = 0.5) avoids cusps and self-loops
	var t0 := 0.0
	var t1 := t0 + pow(max(p0.distance_to(p1), 0.01), 0.5)
	var t2 := t1 + pow(max(p1.distance_to(p2), 0.01), 0.5)
	var t3 := t2 + pow(max(p2.distance_to(p3), 0.01), 0.5)
	var tt := lerpf(t1, t2, t)
	var a1 := p0 * ((t1 - tt) / (t1 - t0)) + p1 * ((tt - t0) / (t1 - t0))
	var a2 := p1 * ((t2 - tt) / (t2 - t1)) + p2 * ((tt - t1) / (t2 - t1))
	var a3 := p2 * ((t3 - tt) / (t3 - t2)) + p3 * ((tt - t2) / (t3 - t2))
	var b1 := a1 * ((t2 - tt) / (t2 - t0)) + a2 * ((tt - t0) / (t2 - t0))
	var b2 := a2 * ((t3 - tt) / (t3 - t1)) + a3 * ((tt - t1) / (t3 - t1))
	return b1 * ((t2 - tt) / (t2 - t1)) + b2 * ((tt - t1) / (t2 - t1))


func _resample(dense: PackedVector2Array) -> void:
	var total := 0.0
	var n := dense.size()
	for i in n:
		total += dense[i].distance_to(dense[(i + 1) % n])
	var count := maxi(16, int(round(total / SAMPLE_STEP)))
	step = total / count
	length = total
	var seg := 0
	var seg_start := 0.0
	var seg_len := dense[0].distance_to(dense[1 % n])
	for k in count:
		var target := k * step
		while seg_start + seg_len < target and seg < n - 1:
			seg_start += seg_len
			seg += 1
			seg_len = dense[seg].distance_to(dense[(seg + 1) % n])
		var f := 0.0 if seg_len <= 0.0001 else (target - seg_start) / seg_len
		samples.append(dense[seg].lerp(dense[(seg + 1) % n], clampf(f, 0.0, 1.0)))
	var m := samples.size()
	var mn := samples[0]
	var mx := samples[0]
	for i in m:
		var tg := (samples[(i + 1) % m] - samples[(i - 1 + m) % m]).normalized()
		tangents.append(tg)
		normals.append(Vector2(-tg.y, tg.x))
		mn = mn.min(samples[i]); mx = mx.max(samples[i])
	bounds = Rect2(mn, mx - mn)


func _compute_curvature() -> void:
	var m := samples.size()
	var raw := PackedFloat32Array()
	raw.resize(m)
	for i in m:
		var a := tangents[(i - 1 + m) % m].angle()
		var b := tangents[(i + 1) % m].angle()
		raw[i] = wrapf(b - a, -PI, PI) / (2.0 * step)
	curvature.resize(m)
	radius.resize(m)
	var w := CURVATURE_WINDOW
	for i in m:
		var s := 0.0
		for j in range(-w, w + 1):
			s += raw[(i + j + m) % m]
		var k := s / (2 * w + 1)
		curvature[i] = k
		radius[i] = minf(1.0 / maxf(absf(k), 0.0002), 5000.0)


func _detect_corners() -> void:
	var m := samples.size()
	const CORNER_R := 260.0
	# find a starting index that's not inside a corner
	var start := 0
	for i in m:
		if radius[i] > CORNER_R:
			start = i
			break
	var in_corner := false
	var c := {}
	for jj in range(m + 1):
		var i := (start + jj) % m
		var is_c := radius[i] < CORNER_R
		if is_c and not in_corner:
			in_corner = true
			c = {"start": i, "apex": i, "end": i, "min_radius": radius[i], "dir": signf(curvature[i])}
		elif is_c and in_corner:
			c["end"] = i
			if radius[i] < c["min_radius"]:
				c["min_radius"] = radius[i]
				c["apex"] = i
				c["dir"] = signf(curvature[i])
		elif not is_c and in_corner:
			in_corner = false
			corners.append(c)


## Overtaking opportunities: heavy braking zones that follow a straight.
func _detect_overtake_zones() -> void:
	var m := ref_profile.size()
	if m == 0:
		return
	var vmax := 0.0
	for v in ref_profile:
		vmax = maxf(vmax, v)
	var i := 0
	while i < m:
		var drop := ref_profile[i] - ref_profile[(i + 12) % m]   # speed lost over ~48 m
		if drop > 6.0:
			# straight length before this braking point
			var straight := 0
			var j := i
			while straight < m and ref_profile[(j - 1 + m) % m] >= ref_profile[j] - 0.01 and ref_profile[(j - 1 + m) % m] > vmax * 0.75:
				straight += 1
				j = (j - 1 + m) % m
			var entry_v := ref_profile[i]
			var min_v := entry_v
			var k := i
			while k < i + 120 and ref_profile[(k + 1) % m] <= ref_profile[k % m] + 0.01:
				k += 1
				min_v = minf(min_v, ref_profile[k % m])
			var strength := clampf((straight * step) / 900.0, 0.0, 1.0) * 0.6 + clampf((entry_v - min_v) / 50.0, 0.0, 1.0) * 0.4
			if strength > 0.12:
				overtake_zones.append({"index": i, "strength": strength})
			i = k + 5
		else:
			i += 1


func _build_lookups() -> void:
	var m := samples.size()
	corner_start_at.resize(m)
	zone_at.resize(m)
	corner_start_at.fill(-1)
	zone_at.fill(-1)
	for ci in corners.size():
		corner_start_at[corners[ci]["start"]] = ci
	for zi in overtake_zones.size():
		var zidx: int = overtake_zones[zi]["index"]
		for d in 4:
			zone_at[(zidx - d + m) % m] = zi


func _compute_stats() -> void:
	var m := ref_profile.size()
	var lap_time := 0.0
	var full_throttle := 0.0
	var vmax := 0.0
	for v in ref_profile:
		vmax = maxf(vmax, v)
	var tire_stress := 0.0
	var hs_time := 0.0
	var longest := 0.0
	var run := 0.0
	for i in m:
		var v := maxf(ref_profile[i], 1.0)
		var dt := step / v
		lap_time += dt
		var accelerating := ref_profile[(i + 1) % m] >= ref_profile[i] - 0.05
		if accelerating and (v > vmax * 0.97 or radius[i] > 400.0):
			full_throttle += dt
		var lat := v * v / radius[i]
		tire_stress += lat * step
		if radius[i] < 400.0 and v > 50.0:
			hs_time += dt
		if radius[i] > 500.0:
			run += step
			longest = maxf(longest, run)
		else:
			run = 0.0
	var zone_sum := 0.0
	for z in overtake_zones:
		zone_sum += z["strength"]
	var width_f := clampf((width - 9.0) / 10.0, 0.0, 1.0)
	stats = {
		"length_m": length,
		"corners": corners.size(),
		"ref_lap_time": lap_time,
		"avg_speed_kph": length / lap_time * 3.6,
		"top_speed_kph": vmax * 3.6,
		"full_throttle_pct": full_throttle / lap_time * 100.0,
		"longest_straight_m": longest,
		# 0..100 ratings
		"tire_wear": clampf(tire_stress / length / 0.55, 0.0, 100.0),
		"downforce": clampf(hs_time / lap_time * 260.0, 0.0, 100.0),
		"overtaking": clampf(zone_sum * 28.0 + width_f * 30.0, 0.0, 100.0),   # higher = easier
		"difficulty": clampf(corners.size() * 3.0 + (14.0 - width) * 5.0 + _slow_corner_count() * 3.0, 0.0, 100.0),
	}


func _slow_corner_count() -> int:
	var n := 0
	for c in corners:
		if c["min_radius"] < 40.0:
			n += 1
	return n


## Normalised weights of which car dimensions matter here (used for UI + AI decisions).
func demands() -> Dictionary:
	var m := ref_profile.size()
	var t_top := 0.0; var t_low := 0.0; var t_high := 0.0; var t_brake := 0.0; var t_trac := 0.0
	for i in m:
		var v := maxf(ref_profile[i], 1.0)
		var dt := step / v
		var nxt := ref_profile[(i + 1) % m]
		if nxt < v - 0.05:
			t_brake += dt
		elif radius[i] < 80.0:
			t_low += dt
		elif radius[i] < 400.0:
			t_high += dt
		elif v < 60.0:
			t_trac += dt
		else:
			t_top += dt
	var tot := t_top + t_low + t_high + t_brake + t_trac
	return {"top_speed": t_top / tot, "low_speed_cornering": t_low / tot, "high_speed_cornering": t_high / tot,
		"braking": t_brake / tot, "traction": t_trac / tot}


# ---------------------------------------------------------------- queries

func index_at(dist: float) -> int:
	var d := fposmod(dist, length)
	return int(d / step) % samples.size()


func position_at(dist: float, lateral: float = 0.0) -> Vector2:
	var d := fposmod(dist, length)
	var f := d / step
	var i := int(f) % samples.size()
	var j := (i + 1) % samples.size()
	var t := f - floorf(f)
	var p := samples[i].lerp(samples[j], t)
	if lateral != 0.0:
		p += normals[i].lerp(normals[j], t).normalized() * lateral
	return p


func tangent_at(dist: float) -> Vector2:
	return tangents[index_at(dist)]


func sector_of(dist: float) -> int:
	var f := fposmod(dist, length) / length
	if f < float(sectors[0]):
		return 0
	if f < float(sectors[1]):
		return 1
	return 2


## Basic validity check for player-made tracks.
func validate() -> Array:
	var problems := []
	if points.size() < 4:
		problems.append("Track needs at least 4 control points.")
	if length < 800.0:
		problems.append("Track is too short (min 800 m).")
	if _self_intersects():
		problems.append("Track crosses itself.")
	return problems


func _self_intersects() -> bool:
	var m := samples.size()
	var stride := 3
	var segs := []
	for i in range(0, m, stride):
		segs.append([samples[i], samples[(i + stride) % m]])
	var n := segs.size()
	for a in n:
		for b in range(a + 2, n):
			if a == 0 and b == n - 1:
				continue
			if Geometry2D.segment_intersects_segment(segs[a][0], segs[a][1], segs[b][0], segs[b][1]) != null:
				return true
	return false
