class_name TrackData
extends RefCounted
## Track definition + generated geometry.
##
## Editable data (what the track editor changes and what is saved):
##   points       closed centerline control points (metres)
##   pt_width / pt_runoff / pt_bank / pt_elev   per control point properties
##   start_u      spline parameter of the start/finish line (point index + t)
##   sectors      lap fractions where sector 2 and 3 start
##   drs_zones    [[u_start, u_end], ...] spline parameters
##   pit          {"entry": u, "exit": u, "side": ±1} or {}
## Everything else (samples, racing line, curvature, corners, braking/overtaking zones,
## DRS ranges, pit lane path, stats) is generated by build().

const FORMAT := 2
const SAMPLE_STEP := 4.0
const SPLINE_SUBDIV := 24
const CURVATURE_WINDOW := 4
const DEFAULT_RUNOFF := 20.0
const BRIDGE_CLEARANCE := 5.0
const MIN_WIDTH := 8.0
const MAX_WIDTH := 30.0
const CAR_HALF_WIDTH := 1.0
const RL_STRIDES := [32, 16, 8, 4, 2]
const RL_ITERS := [80, 60, 50, 40, 30]

static var _cache: Dictionary = {}

var id: String = ""
var name: String = ""
var location: String = ""
var width: float = 13.0                 # default width for new points
var default_laps: int = 12
var sectors: Array = [0.333, 0.667]
var builtin: bool = false
var points: PackedVector2Array = PackedVector2Array()
var pt_width: PackedFloat32Array = PackedFloat32Array()
var pt_runoff: PackedFloat32Array = PackedFloat32Array()
var pt_bank: PackedFloat32Array = PackedFloat32Array()     # degrees, + = banked towards the inside of the corner
var pt_elev: PackedFloat32Array = PackedFloat32Array()     # metres
var start_u: float = 0.0
var drs_zones: Array = []
var pit: Dictionary = {}
var use_racing_line := true             # editor turns this off while dragging for speed

# ---------------------------------------------------------------- generated
var samples: PackedVector2Array = PackedVector2Array()     # centerline
var tangents: PackedVector2Array = PackedVector2Array()
var normals: PackedVector2Array = PackedVector2Array()
var sample_u: PackedFloat32Array = PackedFloat32Array()
var width_at: PackedFloat32Array = PackedFloat32Array()
var runoff_at: PackedFloat32Array = PackedFloat32Array()
var bank_at: PackedFloat32Array = PackedFloat32Array()
var elev_at: PackedFloat32Array = PackedFloat32Array()
var grade_at: PackedFloat32Array = PackedFloat32Array()    # rise / run
var line_offset: PackedFloat32Array = PackedFloat32Array() # racing line lateral offset from centerline
var line_points: PackedVector2Array = PackedVector2Array()
var curvature: PackedFloat32Array = PackedFloat32Array()   # of the racing line, signed 1/m
var radius: PackedFloat32Array = PackedFloat32Array()      # of the racing line, m
var length: float = 0.0
var step: float = SAMPLE_STEP
var corners: Array = []           # [{start, apex, end, min_radius, dir}]
var overtake_zones: Array = []    # [{index, strength}]
var braking_zones: Array = []     # [{start, end}] sample indices where the reference car brakes
var ref_profile: PackedFloat32Array = PackedFloat32Array()
var corner_start_at: PackedInt32Array = PackedInt32Array()
var zone_at: PackedInt32Array = PackedInt32Array()
var drs_ranges: Array = []        # [{start, end, detect, length}] lap distances
var drs_at: PackedInt32Array = PackedInt32Array()
var drs_detect_at: PackedInt32Array = PackedInt32Array()
var pit_entry_dist: float = -1.0
var pit_exit_dist: float = -1.0
var pit_path: PackedVector2Array = PackedVector2Array()
var crossings: Array = []         # [{a, b}] bridge crossings (sample indices, a = lower)
var overlaps: Array = []          # sample indices where the track overlaps itself at ground level
var stats: Dictionary = {}
var bounds: Rect2 = Rect2()

var _dpts := PackedVector2Array()
var _du := PackedFloat32Array()
var _dw := PackedFloat32Array()
var _dr := PackedFloat32Array()
var _db := PackedFloat32Array()
var _de := PackedFloat32Array()
var _cum := PackedFloat64Array()
var _d_start := 0.0
var _total := 0.0


# ================================================================ serialisation

static func from_dict(d: Dictionary, racing_line: bool = true) -> TrackData:
	var t := TrackData.new()
	t.use_racing_line = racing_line
	t.id = d.get("id", "")
	t.name = d.get("name", "Unnamed")
	t.location = d.get("location", "")
	t.width = clampf(float(d.get("width", 13)), MIN_WIDTH, MAX_WIDTH)
	t.default_laps = int(d.get("default_laps", 12))
	t.sectors = d.get("sectors", [0.333, 0.667]).duplicate()
	t.builtin = bool(d.get("builtin", false))
	t.start_u = float(d.get("start_u", 0.0))
	var props: Array = d.get("props", [])
	var pts: Array = d.get("points", [])
	for i in pts.size():
		t.points.append(Vector2(float(pts[i][0]), float(pts[i][1])))
		var pr: Array = props[i] if i < props.size() else []
		t.pt_width.append(float(pr[0]) if pr.size() > 0 else t.width)
		t.pt_runoff.append(float(pr[1]) if pr.size() > 1 else DEFAULT_RUNOFF)
		t.pt_bank.append(float(pr[2]) if pr.size() > 2 else 0.0)
		t.pt_elev.append(float(pr[3]) if pr.size() > 3 else 0.0)
	for z in d.get("drs", []):
		t.drs_zones.append([float(z[0]), float(z[1])])
	var p: Dictionary = d.get("pit", {})
	if not p.is_empty():
		t.pit = {"entry": float(p["entry"]), "exit": float(p["exit"]), "side": int(p.get("side", 1))}
	t.build()
	# older / generated files without explicit DRS or pit data get sensible defaults
	if not d.has("drs") and t.length > 0.0:
		t.auto_drs()
	if not d.has("pit") and t.length > 0.0:
		t.auto_pit()
	return t


## Cached load of a track from the database (built-in or user track).
static func load_id(track_id: String) -> TrackData:
	var d := DataDB.get_track(track_id)
	if d.is_empty():
		push_error("Track not found: " + track_id)
		return null
	var h := JSON.stringify(d).hash()
	var c: Dictionary = _cache.get(track_id, {})
	if not c.is_empty() and c["hash"] == h:
		return c["track"]
	var t := from_dict(d)
	_cache[track_id] = {"hash": h, "track": t}
	return t


static func clear_cache() -> void:
	_cache.clear()


func to_dict() -> Dictionary:
	var pts := []
	var props := []
	for i in points.size():
		pts.append([snappedf(points[i].x, 0.1), snappedf(points[i].y, 0.1)])
		props.append([snappedf(pt_width[i], 0.1), snappedf(pt_runoff[i], 0.1), snappedf(pt_bank[i], 0.1), snappedf(pt_elev[i], 0.1)])
	var drs := []
	for z in drs_zones:
		drs.append([snappedf(z[0], 0.0001), snappedf(z[1], 0.0001)])
	var out := {"format": FORMAT, "id": id, "name": name, "location": location, "width": width,
		"default_laps": default_laps, "sectors": sectors, "start_u": snappedf(start_u, 0.0001),
		"points": pts, "props": props, "drs": drs, "pit": {}}
	if not pit.is_empty():
		out["pit"] = {"entry": snappedf(pit["entry"], 0.0001), "exit": snappedf(pit["exit"], 0.0001), "side": pit["side"]}
	return out


func duplicate_track() -> TrackData:
	var d := to_dict()
	d["builtin"] = false
	return from_dict(d, use_racing_line)


# ================================================================ build

func build() -> void:
	_clear_generated()
	if points.size() < 3:
		return
	_ensure_props()
	_spline_dense()
	_resample()
	_compute_racing_line()
	_compute_curvature()
	_compute_grade()
	_detect_corners()
	ref_profile = PerformanceModel.speed_profile(self, PerformanceModel.reference_params())
	_detect_braking_zones()
	_detect_overtake_zones()
	_check_overlaps()
	_build_lookups()
	rebuild_features()


## Rebuilds only things that depend on start/finish-independent anchors (DRS, pit) + stats.
func rebuild_features() -> void:
	if length <= 0.0:
		return
	_build_drs()
	_build_pit()
	_compute_stats()


func _clear_generated() -> void:
	# (packed arrays are value types: clear each member explicitly)
	samples.clear(); tangents.clear(); normals.clear(); line_points.clear()
	sample_u.clear(); width_at.clear(); runoff_at.clear(); bank_at.clear(); elev_at.clear()
	grade_at.clear(); line_offset.clear(); curvature.clear(); radius.clear(); ref_profile.clear()
	corners.clear(); overtake_zones.clear(); braking_zones.clear(); drs_ranges.clear()
	crossings.clear(); overlaps.clear(); pit_path.clear()
	length = 0.0
	stats = {}


func _ensure_props() -> void:
	var n := points.size()
	while pt_width.size() < n:
		pt_width.append(width)
	while pt_runoff.size() < n:
		pt_runoff.append(DEFAULT_RUNOFF)
	while pt_bank.size() < n:
		pt_bank.append(0.0)
	while pt_elev.size() < n:
		pt_elev.append(0.0)
	pt_width.resize(n); pt_runoff.resize(n); pt_bank.resize(n); pt_elev.resize(n)


## Closed centripetal Catmull-Rom through all control points, with interpolated properties.
func _spline_dense() -> void:
	_dpts.clear(); _du.clear(); _dw.clear(); _dr.clear(); _db.clear(); _de.clear()
	var n := points.size()
	for i in n:
		var p0 := points[(i - 1 + n) % n]
		var p1 := points[i]
		var p2 := points[(i + 1) % n]
		var p3 := points[(i + 2) % n]
		for s in SPLINE_SUBDIV:
			var t := float(s) / SPLINE_SUBDIV
			_dpts.append(_catmull(p0, p1, p2, p3, t))
			_du.append(i + t)
			var st := smoothstep(0.0, 1.0, t)
			var i2 := (i + 1) % n
			_dw.append(lerpf(pt_width[i], pt_width[i2], st))
			_dr.append(lerpf(pt_runoff[i], pt_runoff[i2], st))
			_db.append(lerpf(pt_bank[i], pt_bank[i2], st))
			_de.append(lerpf(pt_elev[i], pt_elev[i2], st))


static func _catmull(p0: Vector2, p1: Vector2, p2: Vector2, p3: Vector2, t: float) -> Vector2:
	var t0 := 0.0
	var t1 := t0 + pow(maxf(p0.distance_to(p1), 0.01), 0.5)
	var t2 := t1 + pow(maxf(p1.distance_to(p2), 0.01), 0.5)
	var t3 := t2 + pow(maxf(p2.distance_to(p3), 0.01), 0.5)
	var tt := lerpf(t1, t2, t)
	var a1 := p0 * ((t1 - tt) / (t1 - t0)) + p1 * ((tt - t0) / (t1 - t0))
	var a2 := p1 * ((t2 - tt) / (t2 - t1)) + p2 * ((tt - t1) / (t2 - t1))
	var a3 := p2 * ((t3 - tt) / (t3 - t2)) + p3 * ((tt - t2) / (t3 - t2))
	var b1 := a1 * ((t2 - tt) / (t2 - t0)) + a2 * ((tt - t0) / (t2 - t0))
	var b2 := a2 * ((t3 - tt) / (t3 - t1)) + a3 * ((tt - t1) / (t3 - t1))
	return b1 * ((t2 - tt) / (t2 - t1)) + b2 * ((tt - t1) / (t2 - t1))


func _resample() -> void:
	var n := _dpts.size()
	_cum.resize(n + 1)
	_cum[0] = 0.0
	for i in n:
		_cum[i + 1] = _cum[i] + _dpts[i].distance_to(_dpts[(i + 1) % n])
	_total = _cum[n]
	_d_start = _arc_at_u(start_u)
	var count := maxi(16, int(round(_total / SAMPLE_STEP)))
	step = _total / count
	length = _total
	var npts := float(points.size())
	for k in count:
		var a := fposmod(_d_start + k * step, _total)
		var j := clampi(_cum.bsearch(a, true) - 1, 0, n - 1)
		var seg := _cum[j + 1] - _cum[j]
		var f := 0.0 if seg <= 0.0001 else (a - _cum[j]) / seg
		var jn := (j + 1) % n
		samples.append(_dpts[j].lerp(_dpts[jn], f))
		sample_u.append(fposmod(_du[j] + f / SPLINE_SUBDIV, npts))
		width_at.append(lerpf(_dw[j], _dw[jn], f))
		runoff_at.append(lerpf(_dr[j], _dr[jn], f))
		bank_at.append(lerpf(_db[j], _db[jn], f))
		elev_at.append(lerpf(_de[j], _de[jn], f))
	var m := samples.size()
	var mn := samples[0]
	var mx := samples[0]
	for i in m:
		var tg := (samples[(i + 1) % m] - samples[(i - 1 + m) % m]).normalized()
		tangents.append(tg)
		normals.append(Vector2(-tg.y, tg.x))
		mn = mn.min(samples[i])
		mx = mx.max(samples[i])
	bounds = Rect2(mn, mx - mn)


func _arc_at_u(u: float) -> float:
	var n := _dpts.size()
	var f := fposmod(u, float(points.size())) * SPLINE_SUBDIV
	var j := int(f) % n
	var frac := f - floorf(f)
	return _cum[j] + frac * (_cum[j + 1] - _cum[j])


## Lap distance (from the start/finish line) of a spline parameter.
func u_to_dist(u: float) -> float:
	return fposmod(_arc_at_u(u) - _d_start, _total)


## Spline parameter at a lap distance.
func dist_to_u(dist: float) -> float:
	var m := samples.size()
	var f := fposmod(dist, length) / step
	var i := int(f) % m
	var a := sample_u[i]
	var b := sample_u[(i + 1) % m]
	var npts := float(points.size())
	if b < a - npts * 0.5:
		b += npts
	return fposmod(lerpf(a, b, f - floorf(f)), npts)


# ---------------------------------------------------------------- racing line

## Minimum-curvature racing line inside the track limits (multi-resolution relaxation).
func _compute_racing_line() -> void:
	var m := samples.size()
	line_offset.resize(m)
	line_offset.fill(0.0)
	if use_racing_line:
		for level in RL_STRIDES.size():
			_relax_level(RL_STRIDES[level], RL_ITERS[level])
	line_points.resize(m)
	for i in m:
		line_points[i] = samples[i] + normals[i] * line_offset[i]


func _relax_level(stride: int, iters: int) -> void:
	var m := samples.size()
	var nc := m / stride
	if nc < 8:
		return
	var idx := PackedInt32Array()
	idx.resize(nc)
	for j in nc:
		idx[j] = int(float(j) * m / nc)
	var c := PackedVector2Array(); c.resize(nc)
	var nrm := PackedVector2Array(); nrm.resize(nc)
	var lim := PackedFloat32Array(); lim.resize(nc)
	var o := PackedFloat32Array(); o.resize(nc)
	for j in nc:
		var i := idx[j]
		c[j] = samples[i]
		nrm[j] = normals[i]
		lim[j] = maxf(width_at[i] * 0.5 - CAR_HALF_WIDTH - 0.6, 0.0)
		o[j] = line_offset[i]
	for it in iters:
		for j in nc:
			var pm2 := c[(j - 2 + nc) % nc] + nrm[(j - 2 + nc) % nc] * o[(j - 2 + nc) % nc]
			var pm1 := c[(j - 1 + nc) % nc] + nrm[(j - 1 + nc) % nc] * o[(j - 1 + nc) % nc]
			var pp1 := c[(j + 1) % nc] + nrm[(j + 1) % nc] * o[(j + 1) % nc]
			var pp2 := c[(j + 2) % nc] + nrm[(j + 2) % nc] * o[(j + 2) % nc]
			var target := (pm1 * 4.0 + pp1 * 4.0 - pm2 - pp2) / 6.0
			o[j] = clampf((target - c[j]).dot(nrm[j]), -lim[j], lim[j])
	# write back with linear interpolation between coarse nodes
	for j in nc:
		var a := idx[j]
		var b := idx[(j + 1) % nc]
		var span := (b - a + m) % m
		if span == 0:
			span = m
		for k in span:
			var i := (a + k) % m
			var lim_i := maxf(width_at[i] * 0.5 - CAR_HALF_WIDTH - 0.6, 0.0)
			line_offset[i] = clampf(lerpf(o[j], o[(j + 1) % nc], float(k) / span), -lim_i, lim_i)


func _compute_curvature() -> void:
	var m := line_points.size()
	var raw := PackedFloat32Array()
	raw.resize(m)
	for i in m:
		var a := (line_points[i] - line_points[(i - 2 + m) % m]).angle()
		var b := (line_points[(i + 2) % m] - line_points[i]).angle()
		var ds := line_points[(i - 2 + m) % m].distance_to(line_points[(i + 2) % m])
		raw[i] = wrapf(b - a, -PI, PI) / maxf(ds * 0.5, 0.5)
	curvature.resize(m)
	radius.resize(m)
	var w := CURVATURE_WINDOW
	for i in m:
		var s := 0.0
		for j in range(-w, w + 1):
			s += raw[(i + j + m) % m]
		var k := s / (2 * w + 1)
		curvature[i] = k
		radius[i] = minf(1.0 / maxf(absf(k), 0.0002), 5000.0)


func _compute_grade() -> void:
	var m := samples.size()
	grade_at.resize(m)
	for i in m:
		var a := elev_at[(i - 3 + m) % m]
		var b := elev_at[(i + 3) % m]
		grade_at[i] = clampf((b - a) / (6.0 * step), -0.3, 0.3)


func _detect_corners() -> void:
	var m := samples.size()
	const CORNER_R := 260.0
	var start := 0
	for i in m:
		if radius[i] > CORNER_R:
			start = i
			break
	var in_corner := false
	var c := {}
	for jj in range(m + 1):
		var i := (start + jj) % m
		var is_c := radius[i] < CORNER_R
		if is_c and not in_corner:
			in_corner = true
			c = {"start": i, "apex": i, "end": i, "min_radius": radius[i], "dir": signf(curvature[i])}
		elif is_c and in_corner:
			c["end"] = i
			if radius[i] < c["min_radius"]:
				c["min_radius"] = radius[i]
				c["apex"] = i
				c["dir"] = signf(curvature[i])
		elif not is_c and in_corner:
			in_corner = false
			corners.append(c)


func _detect_braking_zones() -> void:
	var m := ref_profile.size()
	var i := 0
	var guard := 0
	var in_zone := false
	var zs := 0
	while guard < m + 1:
		var idx := (i + guard) % m
		var braking := ref_profile[(idx + 1) % m] < ref_profile[idx] - 0.05
		if braking and not in_zone:
			in_zone = true
			zs = idx
		elif not braking and in_zone:
			in_zone = false
			if (idx - zs + m) % m > 3:
				braking_zones.append({"start": zs, "end": idx})
		guard += 1


func _detect_overtake_zones() -> void:
	var m := ref_profile.size()
	if m == 0:
		return
	var vmax := 0.0
	for v in ref_profile:
		vmax = maxf(vmax, v)
	var i := 0
	while i < m:
		var drop := ref_profile[i] - ref_profile[(i + 12) % m]
		if drop > 6.0:
			var straight := 0
			var j := i
			while straight < m and ref_profile[(j - 1 + m) % m] >= ref_profile[j] - 0.01 and ref_profile[(j - 1 + m) % m] > vmax * 0.75:
				straight += 1
				j = (j - 1 + m) % m
			var entry_v := ref_profile[i]
			var min_v := entry_v
			var k := i
			while k < i + 120 and ref_profile[(k + 1) % m] <= ref_profile[k % m] + 0.01:
				k += 1
				min_v = minf(min_v, ref_profile[k % m])
			var strength := clampf((straight * step) / 900.0, 0.0, 1.0) * 0.6 + clampf((entry_v - min_v) / 50.0, 0.0, 1.0) * 0.4
			if strength > 0.12:
				overtake_zones.append({"index": i, "strength": strength})
			i = k + 5
		else:
			i += 1


## Finds ground-level overlaps (errors) and bridges (crossings with enough height difference).
func _check_overlaps() -> void:
	var m := samples.size()
	var cell := 40.0
	var grid := {}
	for i in m:
		var key := Vector2i(int(floor(samples[i].x / cell)), int(floor(samples[i].y / cell)))
		if not grid.has(key):
			grid[key] = []
		grid[key].append(i)
	var max_w := 0.0
	for w in width_at:
		max_w = maxf(max_w, w)
	var skip := int((max_w * 2.0 + 24.0) / step)
	var seen := {}
	for i in range(0, m, 2):
		var key := Vector2i(int(floor(samples[i].x / cell)), int(floor(samples[i].y / cell)))
		for dx in range(-1, 2):
			for dy in range(-1, 2):
				var bucket = grid.get(key + Vector2i(dx, dy))
				if bucket == null:
					continue
				for j in bucket:
					if j <= i:
						continue
					var sep := mini(j - i, m - (j - i))
					if sep <= skip:
						continue
					var d := samples[i].distance_to(samples[j])
					if d < (width_at[i] + width_at[j]) * 0.5 + 1.0:
						var region := Vector2i(i / 25, j / 25)
						if seen.has(region):
							continue
						seen[region] = true
						if absf(elev_at[i] - elev_at[j]) >= BRIDGE_CLEARANCE:
							crossings.append({"a": i if elev_at[i] < elev_at[j] else j, "b": j if elev_at[i] < elev_at[j] else i})
						else:
							overlaps.append(i)


func _build_lookups() -> void:
	var m := samples.size()
	corner_start_at.resize(m)
	zone_at.resize(m)
	corner_start_at.fill(-1)
	zone_at.fill(-1)
	for ci in corners.size():
		corner_start_at[corners[ci]["start"]] = ci
	for zi in overtake_zones.size():
		var zidx: int = overtake_zones[zi]["index"]
		for d in 4:
			zone_at[(zidx - d + m) % m] = zi


# ---------------------------------------------------------------- DRS / pit

func _build_drs() -> void:
	var m := samples.size()
	drs_ranges.clear()
	drs_at.resize(m)
	drs_detect_at.resize(m)
	drs_at.fill(-1)
	drs_detect_at.fill(-1)
	for zi in drs_zones.size():
		var z: Array = drs_zones[zi]
		var s := u_to_dist(z[0])
		var e := u_to_dist(z[1])
		var span := fposmod(e - s, length)
		var detect := fposmod(s - 120.0, length)
		drs_ranges.append({"start": s, "end": e, "detect": detect, "length": span})
		for k in int(span / step):
			drs_at[index_at(s + k * step)] = zi
		drs_detect_at[index_at(detect)] = zi
		drs_detect_at[index_at(detect + step)] = zi


func _build_pit() -> void:
	pit_path.clear()
	pit_entry_dist = -1.0
	pit_exit_dist = -1.0
	if pit.is_empty():
		return
	pit_entry_dist = u_to_dist(pit["entry"])
	pit_exit_dist = u_to_dist(pit["exit"])
	var span := fposmod(pit_exit_dist - pit_entry_dist, length)
	var side := float(pit["side"])
	var n := int(span / step)
	for k in n + 1:
		var d := pit_entry_dist + k * step
		var i := index_at(d)
		var ramp := smoothstep(0.0, 1.0, clampf(minf(k * step, span - k * step) / 90.0, 0.0, 1.0))
		var off := side * (width_at[i] * 0.5 + lerpf(-2.0, 9.0, ramp))
		pit_path.append(samples[i] + normals[i] * off)


func pit_lane_length() -> float:
	if pit.is_empty():
		return 0.0
	return fposmod(pit_exit_dist - pit_entry_dist, length)


## Places DRS on the longest straights (up to 2).
func auto_drs() -> void:
	drs_zones.clear()
	var m := samples.size()
	var runs := []
	var start := -1
	var first_curve := 0
	for i in m:
		if radius[i] < 600.0:
			first_curve = i
			break
	for jj in m + 1:
		var i := (first_curve + jj) % m
		var straight := radius[i] > 600.0
		if straight and start < 0:
			start = first_curve + jj
		elif not straight and start >= 0:
			runs.append([start, first_curve + jj])
			start = -1
	runs.sort_custom(func(a, b): return (a[1] - a[0]) > (b[1] - b[0]))
	for r in runs.slice(0, 2):
		var len_m: float = (r[1] - r[0]) * step
		if len_m < 450.0:
			continue
		var s: float = r[0] * step + 90.0
		var e: float = r[1] * step - 40.0
		drs_zones.append([dist_to_u(s), dist_to_u(e)])
	rebuild_features()


## Pit lane alongside the start/finish straight, on the side with more free space.
func auto_pit() -> void:
	var entry := dist_to_u(length - minf(320.0, length * 0.12))
	var exit_u := dist_to_u(minf(260.0, length * 0.1))
	var best_side := 1
	var best_clear := -INF
	for side in [1, -1]:
		pit = {"entry": entry, "exit": exit_u, "side": side}
		_build_pit()
		var clear := INF
		for p in pit_path:
			for i in range(0, samples.size(), 3):
				var d := p.distance_to(samples[i]) - width_at[i] * 0.5
				if d < 3.0:
					continue
				clear = minf(clear, d)
		if clear > best_clear:
			best_clear = clear
			best_side = side
	pit = {"entry": entry, "exit": exit_u, "side": best_side}
	rebuild_features()


# ---------------------------------------------------------------- stats

func _compute_stats() -> void:
	var m := ref_profile.size()
	var lap_time := 0.0
	var full_throttle := 0.0
	var vmax := 0.0
	for v in ref_profile:
		vmax = maxf(vmax, v)
	var tire_stress := 0.0
	var hs_time := 0.0
	var longest := 0.0
	var run := 0.0
	var emin := INF
	var emax := -INF
	var max_bank := 0.0
	var max_grade := 0.0
	var w_sum := 0.0
	for i in m:
		var v := maxf(ref_profile[i], 1.0)
		var dt := step / v
		lap_time += dt
		var accelerating := ref_profile[(i + 1) % m] >= ref_profile[i] - 0.05
		if accelerating and (v > vmax * 0.97 or radius[i] > 400.0):
			full_throttle += dt
		tire_stress += minf(v * v / radius[i], 45.0) * step
		if radius[i] < 400.0 and v > 50.0:
			hs_time += dt
		if radius[i] > 500.0:
			run += step
			longest = maxf(longest, run)
		else:
			run = 0.0
		emin = minf(emin, elev_at[i])
		emax = maxf(emax, elev_at[i])
		max_bank = maxf(max_bank, absf(bank_at[i]))
		max_grade = maxf(max_grade, absf(grade_at[i]))
		w_sum += width_at[i]
	var avg_w := w_sum / m
	var zone_sum := 0.0
	for z in overtake_zones:
		zone_sum += z["strength"]
	var width_f := clampf((avg_w - 9.0) / 10.0, 0.0, 1.0)
	var low_runoff := 0
	for c in corners:
		if runoff_at[c["apex"]] < 6.0:
			low_runoff += 1
	stats = {
		"length_m": length,
		"corners": corners.size(),
		"ref_lap_time": lap_time,
		"avg_speed_kph": length / lap_time * 3.6,
		"top_speed_kph": vmax * 3.6,
		"full_throttle_pct": full_throttle / lap_time * 100.0,
		"longest_straight_m": longest,
		"elevation_change_m": emax - emin,
		"max_bank_deg": max_bank,
		"max_grade_pct": max_grade * 100.0,
		"avg_width_m": avg_w,
		"drs_zones": drs_zones.size(),
		"pit_lane_m": pit_lane_length(),
		"bridges": crossings.size(),
		"tire_wear": clampf(tire_stress / length / 0.55, 0.0, 100.0),
		"downforce": clampf(hs_time / lap_time * 260.0, 0.0, 100.0),
		"overtaking": clampf(zone_sum * 28.0 + width_f * 30.0 + drs_zones.size() * 8.0, 0.0, 100.0),
		"difficulty": clampf(corners.size() * 3.0 + (14.0 - avg_w) * 5.0 + _slow_corner_count() * 3.0 + low_runoff * 4.0 + max_grade * 60.0, 0.0, 100.0),
	}


func _slow_corner_count() -> int:
	var n := 0
	for c in corners:
		if c["min_radius"] < 40.0:
			n += 1
	return n


## Normalised share of lap time spent in each phase (used for UI + AI decisions).
func demands() -> Dictionary:
	var m := ref_profile.size()
	var t_top := 0.0; var t_low := 0.0; var t_high := 0.0; var t_brake := 0.0; var t_trac := 0.0
	for i in m:
		var v := maxf(ref_profile[i], 1.0)
		var dt := step / v
		var nxt := ref_profile[(i + 1) % m]
		if nxt < v - 0.05:
			t_brake += dt
		elif radius[i] < 80.0:
			t_low += dt
		elif radius[i] < 400.0:
			t_high += dt
		elif v < 60.0:
			t_trac += dt
		else:
			t_top += dt
	var tot := maxf(t_top + t_low + t_high + t_brake + t_trac, 0.001)
	return {"top_speed": t_top / tot, "low_speed_cornering": t_low / tot, "high_speed_cornering": t_high / tot,
		"braking": t_brake / tot, "traction": t_trac / tot}


# ================================================================ queries

func index_at(dist: float) -> int:
	var d := fposmod(dist, length)
	return int(d / step) % samples.size()


func position_at(dist: float, lateral: float = 0.0) -> Vector2:
	var d := fposmod(dist, length)
	var f := d / step
	var i := int(f) % samples.size()
	var j := (i + 1) % samples.size()
	var t := f - floorf(f)
	var p := samples[i].lerp(samples[j], t)
	if lateral != 0.0:
		p += normals[i].lerp(normals[j], t).normalized() * lateral
	return p


## Car position: racing line + relative lateral offset, kept inside the track (or runoff when off).
func car_position(dist: float, lateral: float, allow_runoff: bool = false) -> Vector2:
	var i := index_at(dist)
	var half := width_at[i] * 0.5 - CAR_HALF_WIDTH
	if allow_runoff:
		half += runoff_at[i]
	var off := clampf(line_offset[i] + lateral, -half, half)
	return position_at(dist, off)


func tangent_at(dist: float) -> Vector2:
	return tangents[index_at(dist)]


func sector_of(dist: float) -> int:
	var f := fposmod(dist, length) / length
	if f < float(sectors[0]):
		return 0
	if f < float(sectors[1]):
		return 1
	return 2


func nearest_sample(world: Vector2) -> int:
	var best := 0
	var best_d := INF
	for i in samples.size():
		var d := samples[i].distance_squared_to(world)
		if d < best_d:
			best_d = d
			best = i
	return best


func nearest_point(world: Vector2, max_dist: float) -> int:
	var best := -1
	var best_d := max_dist * max_dist
	for i in points.size():
		var d := points[i].distance_squared_to(world)
		if d < best_d:
			best_d = d
			best = i
	return best


## {"errors": [...], "warnings": [...]}  (untranslated message keys + args)
func validate() -> Dictionary:
	var errors := []
	var warnings := []
	if points.size() < 4:
		errors.append(["Track needs at least 4 control points.", []])
	if length < 800.0:
		errors.append(["Track is too short (min %d m).", [800]])
	if length > 25000.0:
		errors.append(["Track is too long (max %d km).", [25]])
	if not overlaps.is_empty():
		errors.append(["Track overlaps itself at ground level. Raise one part by %d m or more to build a bridge.", [int(BRIDGE_CLEARANCE)]])
	if length <= 0.0:
		return {"errors": errors, "warnings": warnings}
	var tight := 0
	for c in corners:
		if c["min_radius"] < 9.0:
			tight += 1
	if tight > 0:
		warnings.append(["%d corner(s) are extremely tight; cars will nearly stop.", [tight]])
	var steep := 0.0
	for g in grade_at:
		steep = maxf(steep, absf(g))
	if steep > 0.15:
		warnings.append(["Very steep slope (%d%%). Spread elevation changes over more distance.", [int(steep * 100.0)]])
	var sr := radius[0]
	if sr < 150.0:
		warnings.append(["The start/finish line is in a corner.", []])
	if float(sectors[0]) >= float(sectors[1]) or float(sectors[0]) <= 0.02 or float(sectors[1]) >= 0.98:
		errors.append(["Sector boundaries are invalid.", []])
	if not pit.is_empty():
		var pl := pit_lane_length()
		if pl > length * 0.5:
			errors.append(["Pit lane is longer than half the lap.", []])
		elif pl < 150.0:
			warnings.append(["Pit lane is very short.", []])
		var ed := fposmod(pit_exit_dist - pit_entry_dist, length)
		if fposmod(-pit_entry_dist, length) > ed:
			warnings.append(["The start/finish line is not alongside the pit lane.", []])
	else:
		warnings.append(["No pit lane defined.", []])
	if drs_zones.is_empty():
		warnings.append(["No DRS zones: overtaking will be harder.", []])
	return {"errors": errors, "warnings": warnings}


func is_valid() -> bool:
	return validate()["errors"].is_empty()


# ================================================================ editing operations
# All operations keep anchors (start line, DRS, pit) attached to the same piece of track.

func add_point(pos: Vector2) -> void:
	insert_point(points.size() - 1, pos, 0.5)


## Insert a control point into segment `seg` (between points seg and seg+1) at fraction t.
func insert_point(seg: int, pos: Vector2, t: float = 0.5) -> int:
	var n := points.size()
	if n == 0:
		points.append(pos)
		pt_width.append(width); pt_runoff.append(DEFAULT_RUNOFF); pt_bank.append(0.0); pt_elev.append(0.0)
		return 0
	seg = clampi(seg, 0, n - 1)
	var nxt := (seg + 1) % n
	var at := seg + 1
	points.insert(at, pos)
	pt_width.insert(at, lerpf(pt_width[seg], pt_width[nxt], t))
	pt_runoff.insert(at, lerpf(pt_runoff[seg], pt_runoff[nxt], t))
	pt_bank.insert(at, lerpf(pt_bank[seg], pt_bank[nxt], t))
	pt_elev.insert(at, lerpf(pt_elev[seg], pt_elev[nxt], t))
	_remap_anchors(func(u: float) -> float: return _u_after_insert(u, seg, t, n))
	return at


static func _u_after_insert(u: float, seg: int, t: float, n: int) -> float:
	if u < seg:
		return u
	if u < seg + 1:
		var lt := u - seg
		if lt < t:
			return seg + lt / maxf(t, 0.001)
		return seg + 1 + (lt - t) / maxf(1.0 - t, 0.001)
	return u + 1.0


func remove_point(i: int) -> void:
	var n := points.size()
	if n <= 3:
		return
	var prev := (i - 1 + n) % n
	var new_prev := prev if prev < i else prev - 1
	points.remove_at(i)
	pt_width.remove_at(i); pt_runoff.remove_at(i); pt_bank.remove_at(i); pt_elev.remove_at(i)
	var remap := func(u: float) -> float:
		var a := fposmod(u - prev, float(n))
		if a < 2.0:
			return fposmod(new_prev + a * 0.5, float(n - 1))
		var k := int(floor(u))
		var k2 := k if k < i else k - 1
		return fposmod(u - (k - k2), float(n - 1))
	_remap_anchors(remap)


func reverse() -> void:
	var n := points.size()
	points.reverse()
	pt_width.reverse(); pt_runoff.reverse(); pt_bank.reverse(); pt_elev.reverse()
	_remap_anchors(func(u: float) -> float: return fposmod(n - 1 - u, float(n)))
	for z in drs_zones:
		var s: float = z[0]
		z[0] = z[1]
		z[1] = s
	if not pit.is_empty():
		var e: float = pit["entry"]
		pit["entry"] = pit["exit"]
		pit["exit"] = e
		pit["side"] = -int(pit["side"])
	var s1: float = sectors[0]
	var s2: float = sectors[1]
	sectors = [snappedf(1.0 - s2, 0.001), snappedf(1.0 - s1, 0.001)]


func scale_track(f: float) -> void:
	var c := Vector2.ZERO
	for p in points:
		c += p
	c /= maxf(points.size(), 1)
	for i in points.size():
		points[i] = c + (points[i] - c) * f


## One pass of Laplacian smoothing on the control polygon.
func smooth_points(amount: float = 0.35) -> void:
	var n := points.size()
	var out := points.duplicate()
	for i in n:
		var avg := (points[(i - 1 + n) % n] + points[(i + 1) % n]) * 0.5
		out[i] = points[i].lerp(avg, amount)
	points = out


func set_all_width(w: float) -> void:
	width = clampf(w, MIN_WIDTH, MAX_WIDTH)
	for i in pt_width.size():
		pt_width[i] = width


func _remap_anchors(f: Callable) -> void:
	start_u = f.call(start_u)
	for z in drs_zones:
		z[0] = f.call(z[0])
		z[1] = f.call(z[1])
	if not pit.is_empty():
		pit["entry"] = f.call(pit["entry"])
		pit["exit"] = f.call(pit["exit"])


## Converts a freehand stroke (world coords) into control points (RDP simplification).
static func stroke_to_points(stroke: PackedVector2Array, epsilon: float = 10.0, min_spacing: float = 35.0) -> PackedVector2Array:
	if stroke.size() < 4:
		return stroke
	var simp := _rdp(stroke, epsilon)
	var out := PackedVector2Array()
	for p in simp:
		if out.is_empty() or out[out.size() - 1].distance_to(p) >= min_spacing:
			out.append(p)
	if out.size() > 3 and out[0].distance_to(out[out.size() - 1]) < min_spacing:
		out.remove_at(out.size() - 1)
	return out


static func _rdp(pts: PackedVector2Array, eps: float) -> PackedVector2Array:
	if pts.size() < 3:
		return pts
	var a := pts[0]
	var b := pts[pts.size() - 1]
	var max_d := 0.0
	var idx := 0
	for i in range(1, pts.size() - 1):
		var d := _point_line_dist(pts[i], a, b)
		if d > max_d:
			max_d = d
			idx = i
	if max_d > eps:
		var left := _rdp(pts.slice(0, idx + 1), eps)
		var right := _rdp(pts.slice(idx), eps)
		left.remove_at(left.size() - 1)
		left.append_array(right)
		return left
	return PackedVector2Array([a, b])


static func _point_line_dist(p: Vector2, a: Vector2, b: Vector2) -> float:
	var ab := b - a
	if ab.length_squared() < 0.0001:
		return p.distance_to(a)
	var t := clampf((p - a).dot(ab) / ab.length_squared(), 0.0, 1.0)
	return p.distance_to(a + ab * t)


## Starter layouts for the editor.
static func template(kind: String) -> TrackData:
	var t := TrackData.new()
	t.name = "New Track"
	t.location = "Custom"
	t.width = 13.0
	t.default_laps = 12
	var pts := []
	match kind:
		"oval":
			for i in 10:
				var a := TAU * i / 10.0
				pts.append(Vector2(cos(a) * 700.0, sin(a) * 320.0))
		"square":
			pts = [Vector2(0, 0), Vector2(800, 0), Vector2(830, 30), Vector2(830, 570), Vector2(800, 600), Vector2(0, 600), Vector2(-30, 570), Vector2(-30, 30)]
		_:
			for i in 8:
				var a := TAU * i / 8.0
				pts.append(Vector2(cos(a) * 450.0, sin(a) * 450.0))
	for p in pts:
		t.points.append(p)
	t._ensure_props()
	t.build()
	t.auto_drs()
	t.auto_pit()
	return t
